language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang
env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ka4pcE7VYGihpJQrFYESvKpr+q1XTtn4z2Nfaw6464fdQgXXbbZF/7GGxiGWkCW1txwrht+sEp65BqKJcWVV4LBxhGC4TvebALNUAmtjVwyaVgIergUiozeoEblQSyN8/Tw5FEqLK/19CGJxNzxkHul6RlpU38OvLCqu4LQhJhA="
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - zlib1g-dev
      - libfreetype6-dev
      - libopenal1
      - libopenal-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - libboost-dev
      - libsdl1.2-dev
      - libglew-dev
      - libqt4-dev
      - libcppunit-dev
      - libglm-dev
  coverity_scan:
    project:
      name: "arx/ArxLibertatis"
      description: "ArxLibertatis coverity scan"
    notification_email: fabianroth64@googlemail.com
    build_command_prepend: "mkdir build && cd build && cmake --version && cmake .. -DICON_TYPE=none"
    build_command: "make -j1"
    branch_pattern: coverity_scan
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew upgrade cmake boost ; fi
  - if [ "$TRAVIS_OS_NAME" = osx ] ; then brew install zlib freetype sdl2 glew qt5 cppunit glm ; fi
script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then mkdir build ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then cd build ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then cmake --version ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then cmake .. -DICON_TYPE=none -DSTRICT_USE=1 -DBUILD_ALL=1 ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then make -j1 ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]] ; then make check ; fi
branches:
  only:
    - master
    - travis
    - coverity_scan
notifications:
  irc:
    channels:
      - "irc.freenode.net#arxfatalis"
    on_success: change
    on_failure: always
