language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ka4pcE7VYGihpJQrFYESvKpr+q1XTtn4z2Nfaw6464fdQgXXbbZF/7GGxiGWkCW1txwrht+sEp65BqKJcWVV4LBxhGC4TvebALNUAmtjVwyaVgIergUiozeoEblQSyN8/Tw5FEqLK/19CGJxNzxkHul6RlpU38OvLCqu4LQhJhA="
git:
  depth: 1000
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - zlib1g-dev
      - libfreetype6-dev
      - libopenal1
      - libopenal-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - libboost-dev
      - libsdl1.2-dev
      - libglew-dev
      - libqt4-dev
      - libcppunit-dev
      - libglm-dev
  coverity_scan:
    project:
      name: "arx/ArxLibertatis"
      description: "ArxLibertatis coverity scan"
    notification_email: fabianroth64@googlemail.com
    build_command_prepend: "mkdir build && cd build && cmake --version && cmake .. -DICON_TYPE=none -DUNITY_BUILD=false"
    build_command: "make -j1"
    branch_pattern: coverity_scan
script:
  - cd build
  - ls -la cov-int
  - cat cov-int/scm_log.txt
branches:
  only:
    - master
    - travis
    - coverity_scan
notifications:
  irc:
    channels:
      - "irc.freenode.net#arxfatalis"
    on_success: change
    on_failure: always
